export const TEST = 'test';
export const GET_ERRORS = 'GET_ERRORS';
export const DELETE_ERRORS = 'DELETE_ERRORS';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const CREATE_NOTIFICATION = 'CREATE_NOTIFICATION';
export const CREATE_NOTIFICACION_PROCESS = 'CREATE_NOTIFICACION_PROCESS';


export const GET_LIST_DEGREES = 'GET_LIST_DEGRESS'
export const GET_PERSONS_RECORDS = 'GET_PERSONS_RECORDS'
export const GET_PERSON_BY_IDPERSON = 'GET_PERSON_BY_IDPERSON'
export const GET_JOBS_LIST = 'GET_JOBS_LIST'
export const GET_LIST_CURRENCIES = 'GET_LIST_CURRENCIES'